@GameCatalog_HostAddress = http://localhost:5062

GET http://localhost:5062/Games

###
POST http://localhost:5062/Games
Content-Type: application/json

{
    "Title" : "DK Bananza",
    "Price" : 59.99,
    "Publisher" : "Nintendo"
}

###
PUT {{GameCatalog_HostAddress}}/Games/1
Content-Type: application/json

{
    "Title": "E33",
    "Price": 39.99,
    "Publisher": "Sandfall Interactive"
}

###
DELETE http://localhost:5062/Games/2

###
GET http://localhost:5062/Movies

###
POST http://localhost:5062/Movies
Content-Type: application/json

{
    "Title" : "Spider-Man",
    "Genre" : "Superhero, Action",
    "ReleaseYear" : 2026
}

###
PUT http://localhost:5062/Movies/1
Content-Type: application/json

{
    "Title" : "The Drama",
    "Genre" : "Drama",
    "ReleaseYear" : 2026
}

###
DELETE http://localhost:5062/Movies/2